# Generated by Django 2.1 on 2018-08-06 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_course_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='question_text',
        ),
    ]
